#pragma once

//Synchronize with the values in the shader
#define INSTANCE_BUFFER_BINDING_POINT 1
#define GBUFFER_BINDING_POINT 2

#define LIGHT_BINDING_POINT 3
#define SHADOW_INSTANCE_BINDING_POINT 4
#define SHADOW_BINDING_POINT 5
#define SHADOW_TEXT_BINDING_POINT 6
